[target.aarch64-linux-android]
ar = "/Users/syl/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/syl/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
ar = "/Users/syl/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Users/syl/Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi31-clang++"

[build]
target = "aarch64-apple-ios-sim"
# target = "aarch64-linux-android"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]